### ISSUE TITLE
[Bug]: Mismatch versions

### ISSUE THREAD

**Issue by TheAlphaStriker** [Fuzss/diagonalwindows#9]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

8.1.2

### Notes (Required)

The mod is giving a message saying the mod versions are mismatched between a server and client but when it shows the versions they are the same. 
![DiagonalWindows](https://github.com/Fuzss/diagonalwindows/assets/70114912/f25cab00-da74-4998-a829-7a02094823b1)

### latest.log (Optional)

https://gist.github.com/TheAlphaStriker/9307bfc14a1fba4f48cd0813ea4843c4

**Comment by Fuzss** [comment]
Please make sure you are using the latest version of Puzzles Lib on both client and server.

**Comment by TheAlphaStriker** [comment]
The server version of puzzles lib does match the client. It is running 8.1.8 puzzles lib but I was receiving this issue before the newest update of puzzles lib came out on the 19th. Does the newest version of Puzzles lib fix this issue specifically?

**Comment by Fuzss** [comment]
A related issue was fixed so there is a chance your issue is resolved, too.

**Comment by TheAlphaStriker** [comment]
Alright, thanks for the help!

**Comment by TheAlphaStriker** [comment]
It didn't fix the issue, it is occurring with diagonal fences and diagonal windows as well. Sometimes its fine and other times when you launch minecraft and try to log in it will do it so I'm not sure why its not consistent.

**Comment by Fuzss** [comment]
Well in the SnowRealMagic log that mod is missing on the client, so it is expected to cause issues with registry syncing.
I'd recommend doing some isolated tests with SnowRealMagic & Diagonal Fences and/or Diagonal Windows.
